# Generated by Django 5.0.6 on 2024-07-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0002_product_rating_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='../static/images/products/%Y/%m/%d/'),
        ),
    ]
