# Generated by Django 5.0.6 on 2024-07-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/products/%Y/%m/%d/'),
        ),
    ]
