# Generated by Django 5.0.6 on 2024-07-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0004_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='webstore/static/images/products/%Y/%m/%d/'),
        ),
    ]
