# Generated by Django 5.0.6 on 2024-07-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0006_retaileruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RetailerUser',
        ),
    ]
