# Generated by Django 5.0.6 on 2024-07-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0011_retailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval',
            field=models.BooleanField(default=True),
        ),
    ]
