# Generated by Django 5.0.6 on 2024-07-23 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0012_product_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='retailer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='retailer.retailer'),
            preserve_default=False,
        ),
    ]
