# Generated by Django 5.0.6 on 2024-07-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0015_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Placed', 'Order Placed'), ('Order Confirmed', 'Order Confirmed'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Order Placed', max_length=255),
        ),
    ]
