# Generated by Django 5.0.6 on 2024-08-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailer', '0017_alter_order_status_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Order Placed'), (2, 'Order Confirmed'), (3, 'Dispatched'), (4, 'Out for Delivery'), (5, 'Delivered'), (0, 'Cancelled')], default=1),
        ),
    ]
