# Generated by Django 5.0.6 on 2024-07-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registereduser',
            options={'verbose_name': 'Registered User', 'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
