# Generated by Django 5.0.6 on 2024-08-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0006_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='coin',
            field=models.PositiveIntegerField(default=500),
        ),
        migrations.AddField(
            model_name='scrap',
            name='delivery',
            field=models.CharField(default='Unknown', max_length=225),
        ),
        migrations.AddField(
            model_name='scrap',
            name='estimateprice',
            field=models.IntegerField(default='null'),
        ),
        migrations.AddField(
            model_name='scrap',
            name='rewardmethod',
            field=models.CharField(choices=[('coin', 'Coin'), ('cash', 'Cash')], default='coin', max_length=4),
        ),
        migrations.AddField(
            model_name='scrap',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
