# Generated by Django 5.0.6 on 2024-08-30 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0007_registereduser_coin_scrap_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='estimateprice',
            field=models.IntegerField(default='0'),
        ),
    ]
