# Generated by Django 5.0.6 on 2024-08-30 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0008_alter_scrap_estimateprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='estimateprice',
            field=models.IntegerField(default=0),
        ),
    ]
