# Generated by Django 5.0.6 on 2024-08-30 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0011_alter_scrap_estimateprice'),
    ]

    operations = [
    ]
