# Generated by Django 5.0.6 on 2024-08-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0012_auto_20240830_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrap',
            name='estimateprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
