# Generated by Django 5.0.6 on 2024-08-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0013_alter_scrap_estimateprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='estimateprice',
        ),
    ]
