# Generated by Django 5.0.6 on 2024-08-30 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0014_remove_scrap_estimateprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registereduser',
            name='coin',
        ),
    ]
