# Generated by Django 5.0.6 on 2024-08-30 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0015_remove_registereduser_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='rewardmethod',
        ),
        migrations.RemoveField(
            model_name='scrap',
            name='status',
        ),
    ]
